#!/usr/bin/env python3

"""Hurry Asteroid"""

import glob
from pathlib import Path
import feedparser
import dominate
from dominate.tags import a, p, h1, h3, link, img
from dominate.util import raw

# folders set up
config_path = Path.home() / ".config" / "hurryasteroid"

if config_path.is_dir():
    pass
else:
    config_path.mkdir()
    print("config path created")

# document header
doc = dominate.document(title="Hurry Asteroid")
with doc.head:
    link(rel="stylesheet", href="style.css")
    raw('<meta name="viewport" content="width=device-width, initial-scale=1.0" />')

# document body
doc += h1("Hurry Asteroid")

for channel in sorted(config_path.glob("*.rss")):
    with open(channel, encoding="utf-8") as file:
        tagFile = file.name + ".etag"
        modFile = file.name + ".mod"
        linkFile = file.name + ".link"
        fTag = config_path / tagFile
        print(fTag)
        fMod = config_path / modFile
        fLink = config_path / linkFile
        rss = file.read()
        print("======\n" + file.name)
        if not any([Path(fTag).exists(), Path(fMod).exists(), Path(fLink).exists()]):
            d = feedparser.parse(rss.strip())
            doc += h3(d.feed.title)
            doc += p(a(d.entries[0].title, href=d.entries[0].link))
            if hasattr(d, "etag"):
                print("writing tag...")
                with open(fTag, "w", encoding="utf-8") as data:
                    data.write(d.etag)
            elif hasattr(d, "modified"):
                with open(fMod, "w", encoding="utf-8") as data:
                    data.write(d.modified)
            # else:
            with open(fLink, "w", encoding="utf-8") as data:
                data.write(d.entries[0].link)
        else:
            print("has data file")
            if Path(fTag).exists():
                print("data: etag")
                with open(fTag, "r", encoding="utf-8") as data:
                    check = data.read()
                d = feedparser.parse(rss.strip(), etag=check)
                if d.status == 304:
                    print("error 304")
                elif d.etag == check:
                    print("tags match, doing nothing")
                else:
                    with open(fLink, "r", encoding="utf-8") as data:
                        check = data.read()
                    if check == d.entries[0].link:
                        print("entries match, doing nothing")
                    else:
                        print("updating...")
                        doc += h3(d.feed.title)
                        doc += p(a(d.entries[0].title, href=d.entries[0].link))
                        with open(fTag, "w", encoding="utf-8") as data:
                            data.write(d.etag)
            elif Path(fMod).exists():
                print("data: modified")
                with open(fMod, "r", encoding="utf-8") as data:
                    check = data.read()
                d = feedparser.parse(rss.strip(), modified=check)
                if d.status == 304:
                    print("error 304")
                elif d.modified == check:
                    print("tags match, doing nothing")
                else:
                    with open(fLink, "r", encoding="utf-8") as data:
                        check = data.read()
                    if check == d.entries[0].link:
                        print("entries match, doing nothing")
                    else:
                        print("updating...")
                        doc += h3(d.feed.title)
                        doc += p(a(d.entries[0].title, href=d.entries[0].link))
                        with open(fMod, "w", encoding="utf-8") as data:
                            data.write(d.modified)
            elif Path(fLink).exists():
                print("data: link")
                with open(fLink, "r", encoding="utf-8") as data:
                    check = data.read()
                d = feedparser.parse(rss.strip())
                if d.entries[0].link == check:
                    print("nothing to do")
                else:
                    print("updating...")
                    doc += h3(d.feed.title)
                    doc += p(a(d.entries[0].title, href=d.entries[0].link))
                    with open(fLink, "w", encoding="utf-8") as data:
                        data.write(d.entries[0].link)

doc += img("asteroid", src="pic.png")

# debug output
print(doc)

# create file
with open("hurryasteroid.html", "w", encoding="utf-8") as outputFile:
    outputFile.write(str(doc))
