#!/usr/bin/env python3
# add feed file
import sys

if len(sys.argv) < 2:
    print("boo!")
    sys.exit()

k = sys.argv[1] + ".rss"

with open(k, "w", encoding="utf-8") as file:
    file.write(sys.argv[2])
